In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk
from sklearn.linear_model import LogisticRegression as LR
import ipywidgets as widgets

In [3]:
df = pd.read_csv("House_Price_India.csv")
df.head()


id   Date  number of bedrooms  number of bathrooms  living area  \
0  6762810635  42491                   4                 2.50         2920   
1  6762810998  42491                   5                 2.75         2910   
2  6762812605  42491                   4                 2.50         3310   
3  6762812919  42491                   3                 2.00         2710   
4  6762813105  42491                   3                 2.50         2600   

   lot area  number of floors  waterfront present  number of views  \
0      4000               1.5                   0                0   
1      9480               1.5                   0                0   
2     42998               2.0                   0                0   
3      4500               1.5                   0                0   
4      4750               1.0                   0                0   

   condition of the house  ...  Built Year  Renovation Year  Postal Code  \
0                       5  ...        1909                0       122004   
1                       3  ...        1939                0       122004   
2                       3  ...        2001                0       122005   
3                       4  ...        1929                0       122006   
4                       4  ...        1951                0       122007   

   Lattitude  Longitude  living_area_renov  lot_area_renov  \
0    52.8878   -114.470               2470            4000   
1    52.8852   -114.468               2940            6600   
2    52.9532   -114.321               3350           42847   
3    52.9047   -114.485               2060            4500   
4    52.9133   -114.590               2380            4750   

   Number of schools nearby  Distance from the airport    Price  
0                         2                         51  1400000  
1                         1                         53  1200000  
2                         3                         76   838000  
3                         1                         51   805000  
4                         1                         67   790000  

[5 rows x 23 columns]

In [22]:
print(df.columns)

Index(['id', 'Date', 'number of bedrooms', 'number of bathrooms',
       'living area', 'lot area', 'number of floors', 'waterfront present',
       'number of views', 'condition of the house', 'grade of the house',
       'Area of the house(excluding basement)', 'Area of the basement',
       'Built Year', 'Renovation Year', 'Postal Code', 'Lattitude',
       'Longitude', 'living_area_renov', 'lot_area_renov',
       'Number of schools nearby', 'Distance from the airport', 'Price'],
      dtype='object')


In [59]:
df.iloc[0:3,0]

0    6762810635
1    6762810998
2    6762812605
Name: id, dtype: int64

In [58]:
df.loc[0,'id']

6762810635

In [67]:
df.id == 6762810998

0        False
1         True
2        False
3        False
4        False
         ...  
14614    False
14615    False
14616    False
14617    False
14618    False
Name: id, Length: 14619, dtype: bool

In [69]:
df['number of floors']

0        1.5
1        1.5
2        2.0
3        1.5
4        1.0
        ... 
14614    1.0
14615    1.5
14616    1.0
14617    1.0
14618    1.0
Name: number of floors, Length: 14619, dtype: float64

In [10]:
df.groupby('Built Year').lot_area_renov.min()

Built Year
1900    1170
1901    1307
1902    1210
1903    1676
1904    1213
        ... 
2011    1104
2012     758
2013     748
2014    1090
2015    1495
Name: lot_area_renov, Length: 116, dtype: int64

In [23]:
x = np.array([1,2,np.nan,4])
index = np.where(np.isnan(x) == True)
for i in index:
    x[index] = 0
print(x)
print(list(x))


[1. 2. 0. 4.]
[1.0, 2.0, 0.0, 4.0]


In [31]:
A = np.zeros((3,2))
B = np.zeros((3,3))
print(A)
print(B)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [51]:
floattext = widgets.FloatText( description='Enter : ', value=0.0 )


In [26]:
try:
    Product = A*B
except:
    print("The two matrices can't be multiplied")

The two matrices can't be multiplied
