In [38]:
import numpy as np
from numpy.random import default_rng
import random
import ipywidgets as widgets

In [11]:
x = default_rng(42).random((3,3))
print(x)

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]


In [17]:
print(x.transpose())


[[0.77395605 0.69736803 0.7611397 ]
 [0.43887844 0.09417735 0.78606431]
 [0.85859792 0.97562235 0.12811363]]


In [19]:
mat = np.zeros((3,3))
for i in range(0,3) :
    for j in range(0,3):
            mat[i,j] = random.random()
print(mat)

[[0.28572512 0.48888357 0.7116774 ]
 [0.2965327  0.84503556 0.20165448]
 [0.12145902 0.3784792  0.85063786]]


In [22]:
for i in range(0,3):
    for j in range(0,i):
        tmp = mat[i,j]
        mat[i,j] = mat[j,i]
        mat[j,i] = tmp
print(mat)

[[0.28572512 0.2965327  0.12145902]
 [0.48888357 0.84503556 0.3784792 ]
 [0.7116774  0.20165448 0.85063786]]


In [24]:
x = mat
y = default_rng(40).random((3,3))
print(y)

[[0.7298985  0.69341496 0.94192102]
 [0.05965206 0.69052097 0.92239752]
 [0.47568318 0.33839069 0.60188281]]


array([[0.20855034, 0.20562021, 0.1144048 ],
       [0.02916291, 0.58351477, 0.34910827],
       [0.33853297, 0.068238  , 0.5119843 ]])

In [36]:
a = np.array([[1,2,3],])
print(np.repeat(a,3))
print(np.tile(a,3))


[1 1 1 2 2 2 3 3 3]
[[1 2 3 1 2 3 1 2 3]]


In [37]:
b = a.transpose()
print(a)
print(b)
print(str(a.shape) + " " + str(b.shape))

[[1 2 3]]
[[1]
 [2]
 [3]]
(1, 3) (3, 1)


In [55]:
a = np.array([1,2,3])
b = np.array([3,2,1])
print(np.cross(a,b))

[-4  8 -4]


In [ ]:
widgets.IntRangeSlider